* Интро
Шпаргалка, как работает сеть.

Пересылка пакетов от устройства к устройству происходит в несколько
этапов. Предположим, что я пытаюсь послать сообщение через вк.

** Мой компьютер коннектится к сети.

В моем случае сеть - это вай-фай, который раздает роутер [TODO:gmm] - Когда?. Роутер
запоминает мак-адрес моего устройства. Мак-адрес представляет собой
уникальный адрес каждого устройства [TODO:gmm] - на траспортном уровне: компьютера, мобильника и т.д. Даже у
самого роутера есть мак-адрес.

** Мой компьютер устанавливает соединиение с вк.

Для этого он открывает порт ([TODO:gmm] -нет, он коннектится на открытый порт вк) спецом для этого соединения - иначе мы не
разберем, какой пакет пришел от вк, какой от телеги, а какой от
скайпа. Комп формирует первый пакет - запрос на соединение с вк. Он
содержит в себе инфу "от кого" - ip и порт компа -  и "кому" - ip и
порт вк (обычно порт 80).

Комп посылает пакет по сети. Пакет доходит до роутера. Роутер понимает,
что этот пакет - это запрос на соединение. Он знает, что в случае запроса
соединения может прийти два варианта пакетов: в соединении отказано и
соединение подтверждено. Поэтому роутер запоминает, что если от ip вк
приходит какой-то из пакетов такого вида, то нужно переслать этот пакет
моему компу. Т.е. просто устанавливет соответствие вида "ip вк - ip
устройства".

После этого роутер меняет в пакете в поле "от кого" ip адрес моего компа
на свой, потому все пакеты идут через роутер.

** Пакет отправляется дальше

Т.е. на сервер. Сервер смотрит на ip вк и понимает, в какую страну мы
будет отправлять пакет - для этого у нас есть соглашение о том, в каких
диапазонах ip могут быть немецкие адрес, российские и т.д. ([TODO:gmm] - дополни из нагугленного про BGP) Он в так же
запоминает в своей таблице адресов, что ответные пакеты надо слать на ip
"от кого", а затем заменяет это поле на свой ip. И так дальше по цепочке
серверов до тех пор, пока пакет не дойдет до адресата. А при получении
ответного пакета все ip будут по цепочке изменяться на исходные, чтоб
пакет от вк дошел до компа.
